spring:
  application:
    name: rest-service-2

  zipkin:
#    baseUrl: http://zipkin:9411/
    baseUrl: http://rest-service-collect:9413
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 16007